# Generated by Django 3.2.9 on 2021-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='')),
                ('instructions', models.CharField(max_length=1400)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
