# Generated by Django 3.2.9 on 2021-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsapi', '0002_auto_20211212_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='plants/'),
        ),
    ]
