# Generated by Django 3.2.9 on 2021-12-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsapi', '0005_alter_plant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
