name: CI

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:

  Test-Django:
    runs-on: ubuntu-latest

    container: python:3.8-alpine

    env:
      DB_PASS: ${{ secrets.DBPASS }}
      DJ_KEY: ${{ secrets.DJKEY}}
      ALLOWEDHOSTS: '0.0.0.0'
      DB_HOST: db
      DB_NAME: github_actions
      DB_USER: postgres

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
     
      - name: psycopg2 prerequisites
        run: apt-get install libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
     
      - name: Lint
        run: |
          pip install pylint
          cd backend
          pylint *.py --disable=C0415
     
      - name: Run migrations
        run: |
          cd backend
          python manage.py migrate
     
      - name: Run tests
        run: |
          cd backend
          python manage.py test


  Test-Vue:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
              cd frontend/plantsapp
              npm ci # install dependencies

      - name: Build Vue App
        run: |
              cd frontend/plantsapp
              npm run build --if-present # build the project

      - name: Lint Vue App
        run: |
              cd frontend/plantsapp
              npm run lint
              
      - name: Test Vue App
        run: |
              cd frontend/plantsapp
              npm run test:unit # run the tests
  